[theme]
base="dark"
primaryColor="black"
#backgroundColor="#FFFFFF"
backgroundColor="#181e1f"
#secondaryBackgroundColor="#181e1f"
#secondaryBackgroundColor="#ebda23"
#textColor="#262730"
font="sans serif"